[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

# [[redirects]]
#   from = "/.netlify/functions/*"
#   to = "http://localhost:9000/.netlify/functions/*"
#   status = 200